# Generated by Django 4.0 on 2022-08-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_item_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='design',
            field=models.CharField(choices=[('TLS', 'Top left small'), ('TRS', 'Top right small'), ('CF', 'Centre front'), ('CB', 'Centre back'), ('FB', 'Front and back')], default='CF', max_length=3),
            preserve_default=False,
        ),
    ]
