# Generated by Django 4.0 on 2022-08-22 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_item_design'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='slug',
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(default='New Item', max_length=100),
        ),
    ]
