# Generated by Django 4.0 on 2022-08-23 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_alter_item_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='colour',
            field=models.CharField(choices=[('red', 'Red'), ('wht', 'White'), ('blk', 'Black')], default='White', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='size',
            field=models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=2),
        ),
    ]
