# Generated by Django 4.0 on 2022-08-23 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('polls', '0009_item_quantity_alter_order_items_delete_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='1',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='colour',
            field=models.CharField(choices=[('blk', 'Black'), ('red', 'Red'), ('wht', 'White')], max_length=3),
        ),
    ]
