# Generated by Django 4.0 on 2022-08-23 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_item_user_alter_item_colour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='colour',
            field=models.CharField(choices=[('blk', 'Black'), ('wht', 'White'), ('red', 'Red')], max_length=3),
        ),
    ]
