# Generated by Django 4.0 on 2022-08-25 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_alter_item_colour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='colour',
            field=models.CharField(choices=[('red', 'Red'), ('blk', 'Black'), ('wht', 'White')], max_length=3),
        ),
    ]
