# Generated by Django 4.0 on 2022-08-26 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_alter_item_colour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='colour',
            field=models.CharField(choices=[('wht', 'White'), ('red', 'Red'), ('blk', 'Black')], max_length=3),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(default='New Item', max_length=100, unique=True),
        ),
    ]
