# Generated by Django 4.0 on 2022-08-26 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_alter_item_quantity_billingaddress_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingaddress',
            old_name='countries',
            new_name='country',
        ),
        migrations.AlterField(
            model_name='item',
            name='colour',
            field=models.CharField(choices=[('wht', 'White'), ('blk', 'Black'), ('red', 'Red')], max_length=3),
        ),
    ]
