# Generated by Django 4.0 on 2022-08-26 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_rename_countries_billingaddress_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='colour',
            field=models.CharField(choices=[('blk', 'Black'), ('wht', 'White'), ('red', 'Red')], max_length=3),
        ),
    ]
