# Generated by Django 4.0 on 2022-08-26 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_alter_item_colour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='colour',
            field=models.CharField(choices=[('red', 'Red'), ('wht', 'White'), ('blk', 'Black')], max_length=3),
        ),
    ]
