# Generated by Django 4.0 on 2022-08-28 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_payment_order_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='processing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='refunded',
            field=models.BooleanField(default=False),
        ),
    ]
