# Generated by Django 4.0 on 2022-08-28 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0023_order_delivered_order_processing_order_refunded'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='processing',
            new_name='delivering',
        ),
        migrations.AddField(
            model_name='order',
            name='checkout_failure',
            field=models.CharField(default='None', max_length=30),
            preserve_default=False,
        ),
    ]
